# Starship + Matugen template
# ~/.config/starship.toml

add_newline = false

format = """
$cmd_duration $directory$git_branch$nix_shell
  $character"""

[fill]
symbol = '-'
style = 'fg:{{colors.outline.default.hex}}'

[character]
success_symbol = "[ ](bold fg:{{colors.outline_variant.default.hex}})"
error_symbol = "[ ](bold fg:{{colors.error.default.hex}})"

[package]
disabled = true

[git_branch]
symbol = "󰘬"
truncation_length = 12
truncation_symbol = ""
format = " 󰜥 [](bold fg:{{colors.secondary_container.default.hex}})[$symbol $branch(:$remote_branch)](fg:{{colors.on_secondary_container.default.hex}} bg:{{colors.secondary_container.default.hex}})[ ](bold fg:{{colors.secondary_container.default.hex}})"

[git_commit]
commit_hash_length = 4
tag_symbol = " "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[🍒 PICKING](bold {{colors.error.default.hex}})"

[git_status]
conflicted = " 🏳 "
ahead = " 🏎💨 "
behind = " 😰 "
diverged = " 😵 "
untracked = " 🤷 ‍"
stashed = " 📦 "
modified = " 📝 "
staged = '[++\($count\)]({{colors.primary.default.hex}})'
renamed = " ✍️ "
deleted = " 🗑 "

[nix_shell]
disabled = false
symbol = "󱄅"
impure_msg = "impure"
pure_msg = "pure"
unknown_msg = "shell"
format = ' [](bold fg:{{colors.tertiary_container.default.hex}})[$symbol $state( \($name\))](bold bg:{{colors.tertiary_container.default.hex}} fg:{{colors.on_tertiary_container.default.hex}})[](bold fg:{{colors.tertiary_container.default.hex}})'

[hostname]
ssh_only = false
format = "[•$hostname](bg:{{colors.secondary_container.default.hex}} bold fg:{{colors.on_secondary_container.default.hex}})[](bold fg:{{colors.secondary_container.default.hex}})"
trim_at = ".companyname.com"
disabled = false

[line_break]
disabled = false

[memory_usage]
disabled = true
threshold = -1
symbol = " "
style = "bold dimmed {{colors.primary.default.hex}}"

[time]
disabled = true
format = '🕙[\[ $time \]]($style) '
time_format = "%T"

[username]
style_user = "bold bg:{{colors.secondary_container.default.hex}} fg:{{colors.on_secondary_container.default.hex}}"
style_root = "bold {{colors.error.default.hex}}"
format = "[](bold fg:{{colors.secondary_container.default.hex}})[$user]($style)"
disabled = false
show_always = true

[directory]
home_symbol = " "
read_only = "  "
style = "bg:{{colors.surface_container_high.default.hex}} fg:{{colors.on_surface.default.hex}}"
truncation_length = 2
truncation_symbol = ".../"
format = '[](bold fg:{{colors.surface_container_high.default.hex}})[󰉋 → $path]($style)[](bold fg:{{colors.surface_container_high.default.hex}})'

[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰎈 "
"Pictures" = "  "
"Videos" = "  "
"GitHub" = " 󰊤 "

[cmd_duration]
min_time = 0
format = '[](bold fg:{{colors.primary_container.default.hex}})[󰪢 $duration](bold bg:{{colors.primary_container.default.hex}} fg:{{colors.on_primary_container.default.hex}})[](bold fg:{{colors.primary_container.default.hex}})'