cursor #e6edf7
cursor_text_color #cbd5e1

foreground            #e6edf7
background            #070b14
selection_foreground  #0b0f1a
selection_background  #ff4e66
url_color             #ff4e66

color0   #0b0f1a
color1   #ff3c3f
color2   #76ff4e
color3   #ffd83c
color4   #f62e46
color5   #760010
color6   #ff4e66
color7   #ffe9ec
color8   #a59496
color9   #ff7a7c
color10  #9fff83
color11  #ffe683
color12  #ff687c
color13  #ff8393
color14  #ffafba
color15  #fff6f7
