cursor #d7e5e8
cursor_text_color #bcc9cc

foreground            #d7e5e8
background            #091517
selection_foreground  #093544
selection_background  #a6cce0
url_color             #00daf3

color0   #091517
color1   #ff0158
color2   #00f316
color3   #ffed00
color4   #00cfe6
color5   #006470
color6   #00daf3
color7   #e0fbff
color8   #869b9d
color9   #ff3f82
color10  #4cff5c
color11  #fff24c
color12  #26e8ff
color13  #4cecff
color14  #8cf3ff
color15  #f2fdff
