[config]

[config.wallpaper]
set = true
command = "awww img --transition-type center {{ image }}"

[templates.waybar]
pre_hook = 'rm -rf ~/.config/waybar/colors.css'
input_path = '~/.config/matugen/colors/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = "pkill -SIGUSR2 waybar"

[templates.rofi]
pre_hook = 'rm -rf ~/.config/rofi/type-2/colors/colors.rasi'
input_path = '~/.config/matugen/colors/colors.rasi'
output_path = '~/.config/rofi/type-2/colors/colors.rasi'

[templates.swaync]
pre_hook = 'rm -rf ~/.config/swaync/swaycolors.css'
input_path = '~/.config/matugen/colors/swaycolors.css'
output_path = '~/.config/swaync/swaycolors.css'
post_hook = 'swaync-client -rs'

[templates.kitty]
pre_hook = 'rm -rf ~/.config/kitty/themes/Matugen.conf'
input_path = '~/.config/matugen/colors/kitty-colors.conf'
output_path = '~/.config/kitty/themes/Matugen.conf'
post_hook = 'kitty +kitten themes --reload-in=all Matugen'

[templates.hyprland]
pre_hook = 'rm -rf ~/.config/hypr/modules/colors.lua'
input_path = '~/.config/matugen/colors/hyprland-colors.lua'
output_path = '~/.config/hypr/modules/colors.lua'

[templates.hyprlock]
pre_hook = 'rm -rf ~/.config/hypr/colors.conf'
input_path = '~/.config/matugen/colors/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'

[templates.tmux]
pre_hook = 'rm -rf ~/.config/tmux/tmux-colors.conf'
input_path = '~/.config/matugen/colors/tmux-colors.conf'
output_path = '~/.config/tmux/colors.conf'

[templates.anki]
pre_hook = 'rm -rf ~/.local/share/Anki2/addons21/688199788/themes/Anki.json'
input_path = '~/.config/matugen/colors/anki.json'
output_path = '~/.local/share/Anki2/addons21/688199788/themes/Anki.json'

[templates.yazi]
pre_hook = 'rm -rf ~/.config/yazi/theme.toml'
input_path = '~/.config/matugen/colors/yazi-theme.toml'
output_path = '~/.config/yazi/theme.toml'