[config]

[config.wallpaper]
set = true
command = "awww img --transition-type center {{ image }}"

[templates.waybar]
input_path = '~/.config/matugen/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = "pkill -SIGUSR2 waybar"



