cursor            #ffb599
cursor_text_color #552009

foreground            #f1dfd9
background            #140c09
selection_foreground  #442a20
selection_background  #e7beaf
url_color             #e7beaf

#: black 000000 767676
color0  #1a110e
color8  #3d322f
#: red cc0403 f2201f
color1  #78340e
color9  #e87737
#: green 19cb00 23fd00
color2  #e7beaf
color10 #ffdbce
#: yellow cecb00 fffd00
color3  #d4c78e
color11 #f1e3a8
#: blue 0d73cc 1a8fff
color4  #71361d
color12 #ffb599
#: magenta cb1ed1 fd28ff
color5  #5d4035
color13 #e7beaf
#: cyan 0dcdcd 14ffff
color6  #50471a
color14 #d4c78e
#: white dddddd ffffff
color7  #d8c2bb
color15 #f1dfd9

mark1_foreground #370e00
mark1_background #ffdbce
mark2_foreground #2c160d
mark2_background #ffdbce
mark3_foreground #211b00
mark3_background #f1e3a8

active_tab_foreground #552009
active_tab_background #ffb599
inactive_tab_foreground #ffdbce
inactive_tab_background #71361d

active_border_color #ffb599
inactive_border_color #552009
# bell_border_color #ff5a00