set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g set-clipboard on
set -g default-command "bash"

#Set prefix key
unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

#Split windows 
unbind %
unbind '"'
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

#set vim key navigation
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# reload config
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# start numbering at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6

# Vim style copying
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
unbind -T copy-mode-vi MouseDragEnd1Pane

# Gruvbox Dark palette
thm_bg="#282828"
thm_bg_soft="#32302f"
thm_bg_hard="#1d2021"

thm_fg="#ebdbb2"
thm_fg_dim="#a89984"

thm_red="#fb4934"
thm_green="#b8bb26"
thm_yellow="#fabd2f"
thm_blue="#83a598"
thm_purple="#d3869b"
thm_aqua="#8ec07c"
thm_orange="#fe8019"

thm_gray="#928374"

# Messages
set -g message-style "fg=${thm_aqua},bg=${thm_bg_soft}"
set -g message-command-style "fg=${thm_aqua},bg=${thm_bg_soft}"

# Panes
set -g pane-border-style "fg=${thm_bg_soft}"
set -g pane-active-border-style "fg=${thm_orange}"

# Windows
set -g window-status-style "fg=${thm_fg_dim},bg=${thm_bg}"
set -g window-status-activity-style "fg=${thm_yellow},bg=${thm_bg}"
set -g window-status-separator " "

# Current window
set -g window-status-current-format "#[fg=${thm_bg},bg=${thm_orange},bold]  #I:#W  "

# Other windows
set -g window-status-format "#[fg=${thm_fg_dim},bg=${thm_bg}]  #I:#W  "

# Status bar
set -g status-bg "${thm_bg_hard}"
set -g status-fg "${thm_fg}"

# Right side
set -g status-right "#[fg=${thm_bg},bg=${thm_aqua},bold] #S #[fg=${thm_bg},bg=${thm_blue}] %H:%M #[fg=${thm_bg},bg=${thm_orange}] %Y-%m-%d "

# Left side
set -g status-left "#[fg=${thm_bg},bg=${thm_green},bold] TMUX "
