# =========================
# TERMINAL
# =========================
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g set-clipboard on
set -g default-command "bash"

# =========================
# PREFIX
# =========================
unbind C-b
set -g prefix C-a
bind-key C-a send-prefix

# =========================
# SPLITS
# =========================
unbind %
unbind '"'

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# =========================
# PANE NAVIGATION
# =========================
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R

# =========================
# RELOAD CONFIG
# =========================
unbind r
bind r source-file ~/.config/tmux/tmux.conf \; display-message "tmux reloaded"

# =========================
# WINDOW INDEXING
# =========================
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2
bind -n M-3 select-window -t 3
bind -n M-4 select-window -t 4
bind -n M-5 select-window -t 5
bind -n M-6 select-window -t 6

# =========================
# COPY MODE (VIM)
# =========================
set-window-option -g mode-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

unbind -T copy-mode-vi MouseDragEnd1Pane

# =========================
# THEME
# =========================
source-file ~/.config/tmux/colors.conf

# =========================
# STATUS BAR
# =========================
set -g status on
set -g status-position top
set -g status-justify left

set -g status-left-length 100
set -g status-right-length 140

set -gF status-style \
"bg=#{@thm_bg},fg=#{@thm_fg}"

# =========================
# LEFT
# =========================
set -g status-left "  #S | "

# =========================
# WINDOWS
# =========================
set -g window-status-separator ""

set -gF window-status-style \
"bg=#{@thm_bg},fg=#{@thm_text_variant}"

set -gF window-status-current-style \
"bg=#{@thm_bg},fg=#{@thm_primary}"

set -g window-status-format " #I:#W "

set -g window-status-current-format \
"  #I:#W#{?window_zoomed_flag, 󰍋 ,} "

# =========================
# RIGHT
# =========================
set -g status-right "\
󰉋 #{pane_current_path} | \
#(free -h | awk '/Mem:/ {print \" \"$3\"/\"$2}') | \
#(df -h / | awk 'END{print \"󱛟 \"$4}') | \
#(cat /sys/class/power_supply/BAT0/capacity 2>/dev/null | awk '{print \"󱊣 \"$1\"%\"}') | \
󰥔 %H:%M
"

# =========================
# PANES
# =========================
set -gF pane-border-style \
"fg=#{@thm_outline}"

set -gF pane-active-border-style \
"fg=#{@thm_primary}"

# =========================
# MESSAGES
# =========================
set -gF message-style \
"bg=#{@thm_surface},fg=#{@thm_fg}"

set -gF mode-style \
"bg=#{@thm_primary},fg=#{@thm_inverse_primary}"

# =========================
# GENERAL
# =========================
set -g mouse on
set -g history-limit 100000

# =========================
# CLOCK
# =========================
set -gF clock-mode-colour "#{@thm_primary}"